image: microsoft/dotnet:sdk

pipelines:
  default:
    - step:
        caches:
          - dotnetcore
        script:
          - export PROJECT_NAME=Bespoke.Osc
          - dotnet restore $PROJECT_NAME
          - dotnet build $PROJECT_NAME